from collections.abc import Callable
from typing import Any, TypeGuard, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def slot(func: F) -> F: ...

class ProcessingTemplate:
    def __init_subclass__(cls, **kwargs: Any) -> None: ...

def flow_from_template(template_cls: type[ProcessingTemplate]) -> Callable[..., Any]: ...
def is_template_class(value: Any) -> TypeGuard[type[ProcessingTemplate]]: ...
