"""Invoice parsing facade for v2 domain workflows."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from rdetoolkit.fileops import readf_json
from rdetoolkit.invoicefile import ExcelInvoiceFile, InvoiceFile, SmartTableFile
from rdetoolkit.models.rde2types import RdeInputDirPaths, RdeOutputResourcePath
from rdetoolkit.processing.context import ProcessingContext
from rdetoolkit.processing.processors.invoice import SmartTableInvoiceInitializer
from rdetoolkit.types import InvoiceData


def load_invoice(invoice_path: str | Path, *, schema_path: str | Path | None = None) -> InvoiceData:
    """Load a JSON invoice file into v2 ``InvoiceData``.

    Args:
        invoice_path: Path to ``invoice.json``.
        schema_path: Optional path to ``invoice.schema.json`` to retain on the
            facade payload for downstream validation.

    Returns:
        Parsed invoice data.

    Raises:
        FileNotFoundError: If ``invoice_path`` does not exist.
        ValueError: If the invoice root is not a JSON object.
    """
    path = Path(invoice_path)
    if not path.exists():
        msg = f"Invoice file does not exist: {path}"
        raise FileNotFoundError(msg)
    raw: Any = readf_json(path)
    if not isinstance(raw, dict):
        msg = "Invoice JSON root must be an object"
        raise ValueError(msg)
    schema = readf_json(Path(schema_path)) if schema_path is not None else None
    return InvoiceData(raw=raw, mode="invoice", schema=schema)


def open_invoice_file(invoice_path: str | Path, *, schema_path: str | Path | None = None) -> InvoiceFile:
    """Open a JSON invoice using the legacy invoicefile implementation.

    Args:
        invoice_path: Path to ``invoice.json``.
        schema_path: Optional validation schema path.

    Returns:
        Legacy ``InvoiceFile`` instance.
    """
    schema = Path(schema_path) if schema_path is not None else None
    return InvoiceFile(Path(invoice_path), schema_path=schema)


def open_excel_invoice(invoice_path: str | Path) -> ExcelInvoiceFile:
    """Open an Excel invoice using the legacy invoicefile implementation.

    Args:
        invoice_path: Path to an Excel invoice workbook.

    Returns:
        Legacy ``ExcelInvoiceFile`` instance.
    """
    return ExcelInvoiceFile(Path(invoice_path))


def open_smarttable(table_path: str | Path) -> SmartTableFile:
    """Open a SmartTable using the legacy invoicefile implementation.

    Args:
        table_path: Path to a SmartTable file.

    Returns:
        Legacy ``SmartTableFile`` instance.
    """
    return SmartTableFile(Path(table_path))


def build_excelinvoice_tile_invoice(
    *,
    excel_path: Path,
    invoice_org: Path,
    invoice_schema_path: Path,
    dist_path: Path,
    idx: int,
) -> InvoiceData:
    """Build one ExcelInvoice tile invoice by delegating to v1 overwrite.

    Args:
        excel_path: Excel invoice workbook path.
        invoice_org: Original run-level ``invoice.json`` path.
        invoice_schema_path: Invoice schema path.
        dist_path: Destination tile ``invoice.json`` path.
        idx: Zero-based Excel data row index.

    Returns:
        Parsed tile invoice data.
    """
    dist_path.parent.mkdir(parents=True, exist_ok=True)
    ExcelInvoiceFile.overwrite(
        ExcelInvoiceFile(excel_path),
        invoice_org,
        dist_path,
        invoice_schema_path,
        idx,
    )
    return load_invoice(dist_path, schema_path=invoice_schema_path)


def build_smarttable_tile_invoice(
    *,
    smarttable_rowfile: Path,
    invoice_org: Path,
    invoice_schema_path: Path,
    dist_path: Path,
    rawfiles: tuple[Path, ...] = (),
) -> InvoiceData:
    """Build one SmartTable tile invoice through the v1 initializer.

    Args:
        smarttable_rowfile: Per-row SmartTable CSV generated by the checker.
        invoice_org: Original run-level ``invoice.json`` path.
        invoice_schema_path: Invoice schema path.
        dist_path: Destination tile ``invoice.json`` path.
        rawfiles: Input files associated with the SmartTable row.

    Returns:
        Parsed tile invoice data.
    """
    resource_paths = _smarttable_resource_paths(
        smarttable_rowfile=smarttable_rowfile,
        invoice_org=invoice_org,
        invoice_schema_path=invoice_schema_path,
        dist_path=dist_path,
        rawfiles=rawfiles,
    )
    srcpaths = RdeInputDirPaths(
        inputdata=smarttable_rowfile.parent,
        invoice=invoice_org.parent,
        tasksupport=invoice_schema_path.parent,
    )
    context = ProcessingContext(
        index=_tile_index(dist_path),
        srcpaths=srcpaths,
        resource_paths=resource_paths,
        datasets_function=None,
        mode_name="smarttable",
        smarttable_file=smarttable_rowfile,
    )
    SmartTableInvoiceInitializer().process(context)
    return load_invoice(dist_path, schema_path=invoice_schema_path)


def _smarttable_resource_paths(
    *,
    smarttable_rowfile: Path,
    invoice_org: Path,
    invoice_schema_path: Path,
    dist_path: Path,
    rawfiles: tuple[Path, ...],
) -> RdeOutputResourcePath:
    base = dist_path.parents[1]
    return RdeOutputResourcePath(
        raw=base / "raw",
        nonshared_raw=base / "nonshared_raw",
        rawfiles=rawfiles,
        struct=base / "structured",
        main_image=base / "main_image",
        other_image=base / "other_image",
        meta=base / "meta",
        thumbnail=base / "thumbnail",
        logs=base / "logs",
        invoice=dist_path.parent,
        invoice_schema_json=invoice_schema_path,
        invoice_org=invoice_org,
        smarttable_rowfile=smarttable_rowfile,
        attachment=base / "attachment",
    )


def _tile_index(dist_path: Path) -> str:
    parent = dist_path.parent.parent.name
    return parent if parent.isdigit() else "0000"
