from collections.abc import Callable
from pathlib import Path
from rdetoolkit.runner.mode_resolver import ModeKind
from rdetoolkit.types import InputPaths, InvoiceData, RdeConfig

class InvoiceService:
    def __init__(self) -> None: ...
    def begin_run(self, root: Path) -> None: ...
    def backup(self, mode: ModeKind, *, root: Path, inputdata_path: Path, rawfiles: tuple[Path, ...] = ...) -> Path: ...
    def prepare_tile(self, mode: ModeKind, *, paths: InputPaths, invoice_dir: Path, iteration_index: int, invariant_invoice: InvoiceData | None, invoice_source: Path) -> InvoiceData | None: ...
    def invariant_invoice(self, mode: ModeKind, *, root: Path) -> InvoiceData | None: ...
    def apply_config(self, *, config: RdeConfig, invoice_path: Path, structured_dir: Path, rawfiles: tuple[Path, ...], feature_updater: Callable[[], None] | None = ...) -> None: ...
