from pathlib import Path
from rdetoolkit.types import InputPaths as InputPaths, OutputContext as OutputContext

def resolve_input_paths(input_root: str | Path) -> InputPaths: ...
def resolve_output_paths(output_root: str | Path, *, create: bool = True) -> OutputContext: ...
