from rdetoolkit.errors import RdeExecutionError, RdeInternalError, RdeValidationError

def execution_error(code: int, message: str) -> RdeExecutionError: ...
def validation_error(code: int, message: str) -> RdeValidationError: ...
def internal_error(code: int, message: str) -> RdeInternalError: ...
