from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

@dataclass(frozen=True, slots=True)
class Event:
    node_id: str
    kind: str
    timestamp: float
    payload: dict[str, Any] = ...
    @classmethod
    def node_started(cls, node_id: str) -> Event: ...
    @classmethod
    def node_finished(cls, node_id: str, *, duration: float) -> Event: ...
    @classmethod
    def node_failed(cls, node_id: str, *, error: Exception) -> Event: ...
    @classmethod
    def node_skipped(cls, node_id: str, *, reason: str) -> Event: ...
    def to_dict(self) -> dict[str, Any]: ...

@runtime_checkable
class EventSink(Protocol):
    def emit(self, event: Event) -> None: ...

class MemoryEventSink:
    events: list[Event]
    def __init__(self) -> None: ...
    def emit(self, event: Event) -> None: ...

class FileEventSink:
    def __init__(self, path: Path) -> None: ...
    def emit(self, event: Event) -> None: ...
