from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

@dataclass(frozen=True, slots=True)
class Event:
    run_id: str
    name: str
    timestamp: float = ...
    node_id: str | None = ...
    payload: dict[str, Any] = field(default_factory=dict)
    schema_version: str = ...
    @classmethod
    def run_started(cls, *, run_id: str) -> Event: ...
    @classmethod
    def run_completed(cls, *, run_id: str, status: str | None = None) -> Event: ...
    @classmethod
    def iteration_started(cls, *, run_id: str, index: int) -> Event: ...
    @classmethod
    def iteration_completed(cls, *, run_id: str, index: int) -> Event: ...
    @classmethod
    def node_started(
        cls,
        node_id: str | None = None,
        *,
        run_id: str = ...,
        call_id: str | None = None,
    ) -> Event: ...
    @classmethod
    def node_completed(
        cls,
        node_id: str | None = None,
        *,
        run_id: str = ...,
        call_id: str | None = None,
        duration_ms: float = ...,
    ) -> Event: ...
    @classmethod
    def node_finished(cls, node_id: str, *, duration: float) -> Event: ...
    @classmethod
    def node_failed(
        cls,
        node_id: str | None = None,
        *,
        run_id: str = ...,
        call_id: str | None = None,
        error: Exception | None = None,
        error_type: str = ...,
        error_msg: str = ...,
    ) -> Event: ...
    @classmethod
    def node_skipped(cls, node_id: str, *, reason: str) -> Event: ...
    @classmethod
    def warning(cls, *, run_id: str, code: int, message: str) -> Event: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def kind(self) -> str: ...

@runtime_checkable
class EventSink(Protocol):
    def open(self, run_id: str) -> None: ...
    def emit(self, event: Event) -> None: ...
    def close(self) -> None: ...

class MemoryEventSink:
    run_id: str | None
    events: list[Event]
    closed: bool
    def __init__(self) -> None: ...
    def open(self, run_id: str) -> None: ...
    def emit(self, event: Event) -> None: ...
    def close(self) -> None: ...

class FileEventSink:
    def __init__(self, logs_dir: Path) -> None: ...
    def open(self, run_id: str) -> None: ...
    def emit(self, event: Event) -> None: ...
    def close(self) -> None: ...
