from rdetoolkit.modes.protocol import ModeHandler
from rdetoolkit.runner.mode_resolver import ModeKind

def register(mode: ModeKind, handler: ModeHandler) -> None: ...
def clear() -> None: ...
def handler_for(mode: ModeKind) -> ModeHandler | None: ...
