from pathlib import Path
from rdetoolkit.config import Config as Config
from rdetoolkit.interfaces.filechecker import IInputFileChecker as IInputFileChecker
from rdetoolkit.models.rde2types import RdeInputDirPaths as RdeInputDirPaths, RdeOutputResourcePath as RdeOutputResourcePath

def rdeformat_mode_process(srcpaths: RdeInputDirPaths, resource_paths: RdeOutputResourcePath, datasets_process_function: _CallbackType | None = ..., config: Config | None = ...) -> None: ...
def multifile_mode_process(srcpaths: RdeInputDirPaths, resource_paths: RdeOutputResourcePath, datasets_process_function: _CallbackType | None = ..., config: Config | None = ...) -> None: ...
def excel_invoice_mode_process(srcpaths: RdeInputDirPaths, resource_paths: RdeOutputResourcePath, excel_invoice_file: Path, idx: int, datasets_process_function: _CallbackType | None = ..., config: Config | None = ...) -> None: ...
def invoice_mode_process(srcpaths: RdeInputDirPaths, resource_paths: RdeOutputResourcePath, datasets_process_function: _CallbackType | None = ..., config: Config | None = ...) -> None: ...
def copy_input_to_rawfile_for_rdeformat(resource_paths: RdeOutputResourcePath) -> None: ...
def copy_input_to_rawfile(raw_dir_path: Path, raw_files: tuple[Path, ...]) -> None: ...
def selected_input_checker(src_paths: RdeInputDirPaths, unpacked_dir_path: Path, mode: str | None) -> IInputFileChecker: ...
