from pathlib import Path
from typing import Any, Callable

from rdetoolkit.report.run_report import RunReport

def usage_error(message: str) -> None: ...
def load_config_overrides(config_path: Path | None) -> dict[str, Any] | None: ...
def resolve_flow(flow_ref: str) -> Callable[..., Any]: ...
def determine_exit_code(report: RunReport) -> int: ...
def validate_only(config: dict[str, Any] | None) -> None: ...
def run_flow(flow_ref: str, *, validate_only_requested: bool, config_path: Path | None) -> None: ...
