class ManagedDirectory:
    """Manages a directory with optional index-based subdirectories."""

    path: str
    idx: int

    def __init__(self, base_dir: str, dirname: str, n_digit: int | None = None, idx: int | None = None) -> None: ...
    def create(self) -> None: ...
    def list(self) -> list[str]: ...
    def __call__(self, idx: int) -> "ManagedDirectory": ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class DirectoryOps:
    """Manages a set of directories with optional divided subdirectories."""

    def __init__(self, base_dir: str, n_digit: int | None = None) -> None: ...
    def all(self, idx: int | None = None) -> list[str]: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> ManagedDirectory: ...

def resize_image_aspect_ratio(input_path: str, output_path: str, width: int, height: int) -> None: ...
def detect_encoding(path: str) -> str: ...
def read_from_json_file(path: str) -> str: ...
