import logging
from _typeshed import Incomplete as Incomplete
from logging import Logger
from rdetoolkit.models.rde2types import RdeFsPath as RdeFsPath
from typing import Callable

def get_logger(name: str, *, file_path: RdeFsPath | None = None) -> logging.Logger: ...
def write_job_errorlog_file(code: int, message: str, *, filename: str = 'job.failed') -> None: ...

class CustomLog:
    logger: Incomplete
    def __init__(self, name: str = 'rdeuser') -> None: ...
    def get_logger(self, needlogs: bool = True) -> Logger: ...

def log_decorator() -> Callable: ...
