from pathlib import Path

def make_main_py(path: Path) -> None: ...
def make_requirements_txt(path: Path) -> None: ...
def make_template_json(path: Path) -> None: ...
def cli() -> None: ...
def init() -> None: ...
def version() -> None: ...
