"""Unified callback/flow compatibility matrix for ADR-023.

EP table:
    TC-UM-*-CB-OK: v1 callback SUT succeeds and matches its frozen observation.
    TC-UM-*-CB-USERERR: callback StructuredError exits with frozen job.failed.
    TC-UM-*-CB-VALERR: invalid invoice exits with frozen validation artifact.
    TC-UM-*-FLOW-OK: eager v2 Runner succeeds against the same static input.
        For invoice and multidatatile this compares the full frozen artifact
        observation (output tree minus data/logs/ contents, raw digests, and
        written invoices) through tests/v2/contract/observe.py.
    TC-UM-*-FLOW-USERERR/VALERR: v2 flow errors follow the I6-0 translation
        table (tests/v2/contract/flow_error_table.py, contracts.md §I6-0).
    TC-UM-*-CB-OBS: callback Events/Provenance/RunReport columns are Phase J xfails.

BV table:
    TC-UM-XLS/MDT/SMT-FLOW-CONTINUE-PARTIAL: partial multi-tile policy xfails.
    TC-UM-XLS/MDT/SMT-FLOW-FAIL-FAST: fail-fast policy xfails.
    TC-UM-MDT-FLOW-SIGTERM: representative termination flush contract xfail.

All expected callback values are static JSON produced by ``_generate.py`` at
the ``source.commit`` recorded in each snapshot. The tests execute v1 only as
the SUT; they never create an expected value at test time.
"""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

import pytest

from rdetoolkit.core.flow import flow
from rdetoolkit.exceptions import StructuredError
from rdetoolkit.runner.lifecycle import Runner
from rdetoolkit.types import InputPaths, InvoiceData
from tests.v2.contract.fixtures import _generate
from tests.v2.contract.observe import observe_v2_run, parity_view
from tests.v2.contract.flow_error_table import (
    FAILED_EXIT_CODE,
    VALIDATION_REASON,
    MessageRule,
    expected_divided_indices,
    expected_iteration_count,
    flow_error_cell,
)

_MODES = ("invoice", "excelinvoice", "multidatatile", "rdeformat", "smarttable")
_MODE_IDS = {
    "invoice": "INV",
    "excelinvoice": "XLS",
    "multidatatile": "MDT",
    "rdeformat": "RDF",
    "smarttable": "SMT",
}
_FLOW_INVOICES: list[dict] = []
#: Modes whose FLOW-OK cell compares the complete frozen artifact observation.
#: Session I6-1 proves the shared Core wiring with invoice and multidatatile;
#: excelinvoice and smarttable were measured to match exactly once that wiring
#: existed, and are pinned here so I6-A/B/C cannot regress them silently.
#: rdeformat keeps the narrower comparison until Session I6-A ports the
#: RDEFormat copy semantics.
_FULL_PARITY_MODES = frozenset({"invoice", "multidatatile", "excelinvoice", "smarttable"})


@flow
def _contract_noop_flow(paths: InputPaths, invoice: InvoiceData) -> None:
    """Exercise flow-boundary injection without changing v1-owned artifacts."""
    assert paths.inputdata.is_dir()
    _FLOW_INVOICES.append(deepcopy(invoice.raw))


# Byte-identical to fixtures/_generate.py::_oracle_callback_usererr so the v2
# flow entry raises exactly what the frozen v1 observation recorded.
_USERERR_MESSAGE = (
    "Contract callback failed. Remediation: inspect the fixture callback "
    "and correct its input."
)


@flow
def _contract_usererr_flow(paths: InputPaths, invoice: InvoiceData) -> None:
    """Fail the tile the way the frozen v1 callback oracle fails."""
    assert paths.inputdata.is_dir()
    _FLOW_INVOICES.append(deepcopy(invoice.raw))
    raise StructuredError(_USERERR_MESSAGE, ecode=999)


def _frozen(mode: str, outcome: str) -> dict:
    path = _generate.EXPECTED_ROOT / mode / f"{outcome}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _v2_overrides(mode: str) -> dict:
    """Return the v2 config that reproduces the frozen v1 observation.

    The frozen snapshots were generated by ``_generate._oracle_config``; the
    Runner therefore has to receive the same five artifact switches, otherwise
    a tree comparison would measure a configuration difference instead of an
    implementation difference (ruling #8).
    """
    extended_mode = {
        "multidatatile": "MultiDataTile",
        "rdeformat": "rdeformat",
    }.get(mode)
    return {
        "system": {
            "extended_mode": extended_mode or "invoice",
            "save_raw": True,
            "save_nonshared_raw": True,
            "save_thumbnail_image": False,
            "magic_variable": False,
        },
        "smarttable": {"save_table_file": False},
    }


def _expected_invoice_sequence(invoices: dict[str, object]) -> list[object]:
    def _tile_index(path: str) -> int:
        if path == "data/invoice/invoice.json":
            return 0
        return int(Path(path).parts[2]) + 1

    return [value for path, value in sorted(invoices.items(), key=lambda item: _tile_index(item[0]))]


@pytest.mark.parametrize(
    ("mode", "outcome"),
    [
        pytest.param(mode, outcome, id=f"TC-UM-{_MODE_IDS[mode]}-CB-{outcome.upper()}")
        for mode in _MODES
        for outcome in ("ok", "usererr", "valerr")
    ],
)
def test_callback_entry_matches_frozen_v1_contract(mode: str, outcome: str) -> None:
    """Callback matrix cells compare the v1 SUT with static generated expectations."""
    # Given: the immutable snapshot generated from v1 at its recorded source.commit
    expected = _frozen(mode, outcome)["observed"]

    # When: executing the same v1 path as the subject under test in isolation
    actual = _generate.run_v1_sut(mode, outcome)

    # Then: all frozen artifacts and legacy return fields remain compatible
    assert actual == expected
    if outcome == "ok":
        assert actual["exit_code"] == 0
        assert actual["callback_count"] >= 1
        assert actual["job_failed_error_code"] is None
    else:
        assert actual["exit_code"] == 1
        assert actual["job_failed_error_code"].startswith("ErrorCode=")


@pytest.mark.parametrize(
    "mode",
    [pytest.param(mode, id=f"TC-UM-{_MODE_IDS[mode]}-FLOW-OK") for mode in _MODES],
)
def test_flow_entry_success_matches_frozen_v1_primary_contract(
    mode: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Flow OK cells preserve tile counts and invoice values from frozen v1 output.

    For the modes in ``_FULL_PARITY_MODES`` the comparison is the complete
    artifact observation (output tree, raw digests, written invoices), which is
    what Session I6-1 proves; the remaining modes keep the narrower comparison
    until I6-A/B/C port their mode-specific v1 behavior.
    """
    # Given: a static mode fixture and its v1 callback-success snapshot
    root = tmp_path / mode
    _generate.materialize_sut_case(mode, root)
    monkeypatch.chdir(root)
    _FLOW_INVOICES.clear()
    expected = _frozen(mode, "ok")["observed"]
    runner = Runner(
        root=root,
        inputdata_path=root / "data" / "inputdata",
        # The flow entry contract unpacks into data/temp exactly like
        # ``workflows.run(flow=...)`` and v1 itself (ruling #1).
        unpacked_dir_path=root / "data" / "temp",
    )

    # When: running the eager flow through the v2 Runner
    report = runner.run(_contract_noop_flow, **_v2_overrides(mode))

    # Then: success, tile count, and primary invoice artifacts match frozen v1
    assert report.status == "success"
    assert len(report.iterations) == expected["callback_count"]
    assert _generate.normalize_snapshot(_FLOW_INVOICES, roots=(root,)) == _expected_invoice_sequence(expected["invoices"])

    # And: the proven modes reproduce every frozen artifact observation
    if mode in _FULL_PARITY_MODES:
        assert observe_v2_run(root) == parity_view(expected)


@pytest.mark.parametrize(
    ("mode", "outcome"),
    [
        pytest.param(mode, outcome, id=f"TC-UM-{_MODE_IDS[mode]}-FLOW-{outcome.upper()}")
        for mode in _MODES
        for outcome in ("usererr", "valerr")
    ],
)
def test_flow_error_cells_match_the_i6_0_translation_table(
    mode: str,
    outcome: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Flow error cells follow the contracted v1 -> v2 error translation.

    The frozen v1 observation is checked against the table first, so the table
    can never silently drift away from the oracle it documents.
    """
    # Given: the contracted translation row and the frozen v1 observation
    cell = flow_error_cell(mode, outcome)
    expected = _frozen(mode, outcome)["observed"]
    assert expected["job_failed_error_code"] == f"ErrorCode={cell.v1_code}"
    assert expected["callback_count"] == cell.v1_callback_count
    assert expected["exit_code"] == FAILED_EXIT_CODE
    assert expected["legacy_return"] is None

    root = tmp_path / mode
    _generate.materialize_sut_case(mode, root)
    if outcome == "valerr":
        _generate._invalidate_invoice(root)
    monkeypatch.chdir(root)
    _FLOW_INVOICES.clear()
    runner = Runner(
        root=root,
        inputdata_path=root / "data" / "inputdata",
        # One flow-entry contract: the unpack root is data/temp for every cell
        # of the matrix, exactly as v1 and workflows.run(flow=...) use it.
        unpacked_dir_path=root / "data" / "temp",
    )
    target = _contract_usererr_flow if outcome == "usererr" else _contract_noop_flow

    # When: running the eager flow through the v2 Runner on the same input
    report = runner.run(target, **_v2_overrides(mode))

    # Then: the run fails, and job.failed carries the contracted code
    assert report.status == "failed"
    job_failed = _generate.normalize_snapshot(
        (root / "data" / "job.failed").read_text(encoding="utf-8"),
        roots=(root,),
    )
    assert job_failed.splitlines()[0] == f"ErrorCode={cell.v2_code}"

    # And: the message follows this cell's rule
    if cell.v2_message is MessageRule.V1_VERBATIM:
        assert job_failed == expected["job_failed_text"]
    else:
        assert VALIDATION_REASON in job_failed
        assert cell.v2_code != cell.v1_code

    # And: the flow ran exactly once per tile, or not at all
    tile_count = int(_frozen(mode, "ok")["observed"]["callback_count"])
    assert len(report.iterations) == expected_iteration_count(cell, tile_count)
    assert [iteration["status"] for iteration in report.iterations] == ["failed"] * len(report.iterations)
    assert len(_FLOW_INVOICES) == len(report.iterations)

    # And: only the attempted tiles left a divided/ tree behind
    divided = root / "data" / "divided"
    actual_divided = tuple(sorted(path.name for path in divided.iterdir())) if divided.exists() else ()
    assert actual_divided == expected_divided_indices(cell, tile_count)


@pytest.mark.xfail(strict=False, reason="Phase H/I: multi-tile policy integration is not wired")
@pytest.mark.parametrize(
    ("mode", "policy"),
    [
        pytest.param(mode, policy, id=f"TC-UM-{_MODE_IDS[mode]}-FLOW-{policy}")
        for mode in ("excelinvoice", "multidatatile", "smarttable")
        for policy in ("CONTINUE-PARTIAL", "FAIL-FAST")
    ],
)
def test_multitile_policy_cells_are_placed(mode: str, policy: str) -> None:
    """Multi-tile boundary cells reserve partial and fail-fast behavior."""
    # Given: a multi-tile mode and required future policy
    assert mode in {"excelinvoice", "multidatatile", "smarttable"}
    assert policy in {"CONTINUE-PARTIAL", "FAIL-FAST"}
    # When/Then: Phase H/I owns the unified policy implementation
    pytest.fail("Phase H/I must implement unified multi-tile error policies")


@pytest.mark.xfail(strict=False, reason="Phase J: deterministic SIGTERM flush integration is not wired")
def test_multidatatile_sigterm_cell_is_placed__tc_um_mdt_flow_sigterm() -> None:
    """TC-UM-MDT-FLOW-SIGTERM reserves RunReport/job.failed signal flushing."""
    # Given: the representative MultiDataTile termination contract
    signal_name = "SIGTERM"
    # When/Then: Phase J must wire and verify deterministic signal flushing
    assert signal_name == "SIGTERM"
    pytest.fail("Phase J must implement SIGTERM RunReport/job.failed flushing")


@pytest.mark.xfail(strict=False, reason="Phase J: callback observability is unavailable before unification")
@pytest.mark.parametrize(
    "mode",
    [pytest.param(mode, id=f"TC-UM-{_MODE_IDS[mode]}-CB-OBS") for mode in _MODES],
)
def test_callback_observability_columns_are_placed(mode: str) -> None:
    """Callback Events, Provenance, and RunReport columns remain visible for Phase J."""
    # Given: a legacy callback execution with no unified observability artifacts
    expected_columns = {"events", "provenance", "run_report"}
    assert mode in _MODES
    # When/Then: Phase J must populate every declared comparison column
    assert expected_columns
    pytest.fail("Phase J must add callback Events/Provenance/RunReport parity")
