[build]
rustflags = []

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    "-C",
    "link-arg=-L/usr/arm-linux-gnueabihf/lib",
    "-C",
    "link-arg=-lpython3.10",
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C",
    "link-arg=-L/usr/aarch64-linux-gnu/lib",
    "-C",
    "link-arg=-lpython3.10",
]

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"
rustflags = [
    "-C",
    "link-arg=-L/usr/s390x-linux-gnu/lib",
    "-C",
    "link-arg=-lpython3.10",
]

[target.powerpc64le-unknown-linux-gnu]
linker = "powerpc64le-linux-gnu-gcc"
rustflags = [
    "-C",
    "link-arg=-L/usr/powerpc64le-linux-gnu/lib",
    "-C",
    "link-arg=-lpython3.10",
]
