from pathlib import Path

from rdetoolkit.types import OutputContext

def to_png(source_path: Path, out: OutputContext, filename: str) -> Path: ...
def to_jpeg(source_path: Path, out: OutputContext, filename: str) -> Path: ...
def make_thumbnail(source_path: Path, out: OutputContext, filename: str | None = None) -> Path: ...
def save_main_image(source_path: Path, out: OutputContext, filename: str) -> Path: ...
def copy_raw(source_path: Path, out: OutputContext, filename: str) -> Path: ...
