from pathlib import Path

import pandas as pd

def read_text(path: Path) -> str: ...
def read_csv_with_header(path: Path) -> pd.DataFrame: ...
def read_excel(path: Path) -> pd.DataFrame: ...
def unzip_inputs(src_zip: Path, dst_dir: Path) -> None: ...
