from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "rdetoolkit" / "error_catalog.md"


def _load_catalogs() -> tuple[dict[int, object], dict[int, object]]:
    src_path = str(REPO_ROOT / "src")
    if src_path not in sys.path:
        sys.path.insert(0, src_path)

    from rdetoolkit.errors import ERROR_CATALOG, WARNING_CATALOG

    return ERROR_CATALOG, WARNING_CATALOG


def render() -> str:
    """Render the v2 error catalog documentation from runtime catalogs.

    Returns:
        Markdown content generated from `rdetoolkit.errors`.
    """
    error_catalog, warning_catalog = _load_catalogs()
    lines = [
        "# rdetoolkit v2 Error Catalog",
        "",
        "<!-- Generated by scripts/gen_error_docs.py. Do not edit by hand. -->",
        "",
        "Authority: `local/develop/v2/Design.md` §9.",
        "",
        "## Errors",
        "",
        "| Code | Name | Message template | Remediation |",
        "|------|------|------------------|-------------|",
    ]
    for code in sorted(error_catalog):
        defn = error_catalog[code]
        name = f"~~{defn.name}~~ (retired)" if getattr(defn, "retired", False) else defn.name
        lines.append(f"| {code} | {name} | {defn.message_template} | {defn.remediation} |")

    lines.extend([
        "",
        "## Warnings",
        "",
        "| Code | Name | Message template |",
        "|------|------|------------------|",
    ])
    for code in sorted(warning_catalog):
        defn = warning_catalog[code]
        lines.append(f"| W{code} | {defn.name} | {defn.message_template} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Run the error documentation generator.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated docs are up to date")
    args = parser.parse_args()

    content = render()
    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"missing generated file: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != content:
            print(f"generated file is out of date: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
