from pathlib import Path

from rdetoolkit.types import InputPaths, InvoiceData, OutputContext, RdeConfig

def rde_paths(tmp_path: Path) -> InputPaths: ...
def rde_out(tmp_path: Path) -> OutputContext: ...
def rde_config() -> RdeConfig: ...
def rde_invoice() -> InvoiceData: ...
