from rdetoolkit.core.node import NodeSpec

class DAG:
    def __init__(self) -> None: ...
    def add_node(self, node_id: str, spec: NodeSpec | None = None) -> None: ...
    def add_edge(self, from_id: str, to_id: str, from_port: str, to_port: str) -> None: ...
    def topological_sort(self) -> list[str]: ...
    def predecessors(self, node_id: str) -> list[str]: ...
    def successors(self, node_id: str) -> list[str]: ...
    def node_ids(self) -> list[str]: ...
    def edge_list(self) -> list[tuple[str, str, str, str]]: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def validate(self) -> list[dict[str, str]]: ...
    def get_spec(self, node_id: str) -> NodeSpec | None: ...
