from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from rdetoolkit.core.dag import DAG
from rdetoolkit.core.node import NodeSpec

class FlowDefinitionError(Exception): ...

@dataclass(frozen=True, slots=True)
class FlowResult:
    dag: DAG
    flow_name: str

class OutputProxy:
    node_id: str
    port_name: str
    def __init__(self, node_id: str, port_name: str) -> None: ...
    def __bool__(self) -> bool: ...

class NodeProxy:
    node_spec: NodeSpec
    dag: DAG
    output_names: tuple[str, ...]
    def __init__(self, node_spec: NodeSpec, dag: DAG, output_names: tuple[str, ...]) -> None: ...
    def __iter__(self) -> Any: ...
    def __bool__(self) -> bool: ...
    @property
    def node_id(self) -> str: ...
    @staticmethod
    def record_call(*, node_spec: NodeSpec, dag: DAG, args: dict[str, Any], output_names: tuple[str, ...]) -> NodeProxy: ...

class _Flow:
    def __init__(self, func: Callable[..., Any]) -> None: ...
    def build(self) -> FlowResult: ...
    def execute(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def flow(func: Callable[..., Any]) -> _Flow: ...
def _is_tracing() -> bool: ...
def _trace_node_call(func: Callable[..., Any], *args: Any, **kwargs: Any) -> NodeProxy | Any: ...
