name: cleanup all caches
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install GitHub CLI Cache Extension
        run: gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup
        run: |
          set +e
          echo "Deleting all caches..."
          gh actions-cache list -R $REPO -L 100 | while IFS=$'\t' read -r cacheKey _
          do
            gh actions-cache delete "$cacheKey" -R $REPO --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
